# 基础样式
'$schema' = 'https://starship.rs/config-schema.json'

# 命令间添加空行
add_newline = true

# 扫描文件的超时时间
scan_timeout = 10

# 左侧样式
format = '''
$directory$git_branch$git_commit$git_state$git_metrics$git_status
$character
'''

# 右侧样式
right_format = '''$conda'''
# TODO
# starship 1.13.1 break this line, see https://github.com/starship/starship/issues/4953
# right_format = '''$all'''   # 左侧样式没显示的部分，都在右侧显示

# 上一个命令执行的时间
[cmd_duration]
min_time = 60000  # 1 min

# 当前目录的路径
[directory]
truncation_length = 8                       # 截断到 8 个父目录以内
truncation_symbol = '…/'                    # 被截断的目录的样式
truncate_to_repo  = false                   # 不对 git 仓库进行目录截断
repo_root_style   = 'underline bold cyan'   # git 仓库目录样式
read_only = ' '

# 软件包当前版本
[package]
disabled = true

# 上一个命令退出的状态码
[status]
disabled = false

# 当前 git 仓库的活动分支
[git_branch]
symbol = ' '


# ========== 各种语言的配置 ==========

[c]
format = 'via [$symbol]($style)'
symbol = ' '

[cmake]
format = 'via [$symbol]($style)'

[conda]
symbol = ' '

[nodejs]
format = 'via [$symbol]($style)'
symbol = ' '

[python]
format = 'via [${symbol}${pyenv_prefix}(\($virtualenv\) )]($style)'
style  = 'blue'
symbol = ' '

[rust]
format = 'via [$symbol]($style)'
style  = 'yellow'
symbol = ' '
